export const AGENTS = {
  ORCHESTRATOR: {
    id: 'orchestrator',
    name: 'Orchestrator',
    role: 'Master Controller',
    color: '#6366f1',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    icon: '🧠',
    description: 'Decomposes tasks, routes subtasks to specialists, aggregates results, and drives the feedback loop.',
    inputs: ['User Task', 'Agent Results', 'Verifier Scores', 'Error Reports'],
    outputs: ['Subtask Assignments', 'Re-route Commands', 'Final Response'],
    decisionLogic: [
      'Parse and decompose incoming task into atomic subtasks',
      'Score complexity → assign priority queue',
      'Route subtasks based on agent capability registry',
      'Aggregate partial results into coherent output',
      'Trigger refinement if verifier score < threshold',
      'Escalate to Error Handler on repeated failures (≥3)',
    ],
    position: { x: 50, y: 42 },
  },
  PLANNER: {
    id: 'planner',
    name: 'Planner',
    role: 'Strategic Decomposer',
    color: '#06b6d4',
    bgColor: '#0c1a2e',
    borderColor: '#22d3ee',
    icon: '📋',
    description: 'Converts high-level goals into step-by-step execution plans with dependencies.',
    inputs: ['Task Brief', 'Domain Context', 'Constraints'],
    outputs: ['Execution Plan', 'Dependency Graph', 'Estimated Steps'],
    decisionLogic: [
      'Extract goal, context, and constraints from task brief',
      'Identify required capabilities and data sources',
      'Build DAG of subtask dependencies',
      'Estimate complexity and assign agent types',
      'Flag ambiguous goals → request clarification from Orchestrator',
    ],
    position: { x: 18, y: 18 },
  },
  RESEARCHER: {
    id: 'researcher',
    name: 'Researcher',
    role: 'Information Retrieval',
    color: '#10b981',
    bgColor: '#0a1f16',
    borderColor: '#34d399',
    icon: '🔍',
    description: 'Fetches, filters, and summarizes relevant information from knowledge bases and external tools.',
    inputs: ['Search Queries', 'Source Filters', 'Depth Parameter'],
    outputs: ['Ranked Sources', 'Summaries', 'Confidence Scores'],
    decisionLogic: [
      'Parse query into keywords and semantic vectors',
      'Search internal KB + external APIs in parallel',
      'Rank by relevance × recency × authority',
      'Summarize top-N sources with confidence score',
      'Return "low confidence" flag if score < 0.6',
    ],
    position: { x: 82, y: 18 },
  },
  EXECUTOR: {
    id: 'executor',
    name: 'Executor',
    role: 'Task Performer',
    color: '#f59e0b',
    bgColor: '#1c1208',
    borderColor: '#fbbf24',
    icon: '⚙️',
    description: 'Performs concrete actions: code generation, API calls, document creation, data transforms.',
    inputs: ['Action Spec', 'Context Window', 'Tool Permissions'],
    outputs: ['Action Result', 'Artifacts', 'Execution Logs'],
    decisionLogic: [
      'Validate action spec against tool permission registry',
      'Select tool chain (code / API / transform)',
      'Execute with timeout watchdog (30s default)',
      'Capture stdout, artifacts, and side effects',
      'Retry once on transient failure, else report to Error Handler',
    ],
    position: { x: 18, y: 66 },
  },
  CRITIC: {
    id: 'critic',
    name: 'Critic / Verifier',
    role: 'Quality Gate',
    color: '#ec4899',
    bgColor: '#1f0a16',
    borderColor: '#f472b6',
    icon: '🔬',
    description: 'Evaluates outputs against quality criteria, detects hallucinations, and scores results.',
    inputs: ['Agent Output', 'Original Task', 'Quality Rubric'],
    outputs: ['Quality Score', 'Feedback Report', 'Pass/Fail Decision'],
    decisionLogic: [
      'Compare output against task requirements',
      'Run factual consistency check (vs. Researcher sources)',
      'Score: Accuracy + Completeness + Coherence (0-100)',
      'If score ≥ 80 → PASS; 60-79 → REFINE; <60 → REJECT',
      'Generate structured feedback for refinement loop',
    ],
    position: { x: 82, y: 66 },
  },
  REFINER: {
    id: 'refiner',
    name: 'Refiner',
    role: 'Iterative Improver',
    color: '#a855f7',
    bgColor: '#160a2e',
    borderColor: '#c084fc',
    icon: '✨',
    description: 'Applies Critic feedback to improve outputs through targeted edits and regeneration.',
    inputs: ['Draft Output', 'Critic Feedback', 'Iteration Count'],
    outputs: ['Refined Output', 'Change Summary', 'New Iteration Count'],
    decisionLogic: [
      'Parse structured feedback into edit instructions',
      'Apply targeted patches (surgical edit vs. full regen)',
      'Increment iteration counter',
      'If iteration > MAX_ITER (5) → escalate to Orchestrator',
      'Send refined output back to Critic for re-evaluation',
    ],
    position: { x: 50, y: 72 },
  },
  ERROR_HANDLER: {
    id: 'error_handler',
    name: 'Error Handler',
    role: 'Fault Recovery',
    color: '#ef4444',
    bgColor: '#1f0a0a',
    borderColor: '#f87171',
    icon: '🛡️',
    description: 'Intercepts failures, classifies errors, applies recovery strategies, and logs incidents.',
    inputs: ['Error Report', 'Agent State Snapshot', 'Retry Count'],
    outputs: ['Recovery Plan', 'Fallback Result', 'Incident Log'],
    decisionLogic: [
      'Classify: Transient / Logic / Resource / Timeout / External',
      'Transient → retry with backoff (1s, 2s, 4s)',
      'Logic error → re-route to different agent instance',
      'Resource exhaustion → queue and defer',
      'Unrecoverable → graceful degradation + notify Orchestrator',
    ],
    position: { x: 50, y: 20 },
  },
  MEMORY: {
    id: 'memory',
    name: 'Memory Store',
    role: 'Persistent Context',
    color: '#64748b',
    bgColor: '#0f172a',
    borderColor: '#94a3b8',
    icon: '💾',
    description: 'Maintains short-term working memory and long-term episodic memory across sessions.',
    inputs: ['Agent Outputs', 'User Interactions', 'Session Metadata'],
    outputs: ['Relevant Context', 'Historical Patterns', 'Session State'],
    decisionLogic: [
      'Short-term: sliding window buffer (last 20 interactions)',
      'Long-term: vector DB with semantic retrieval',
      'Eviction: LRU + relevance score < 0.3',
      'Serve top-K relevant memories on agent request',
      'Persist session state for multi-turn continuity',
    ],
    position: { x: 50, y: 90 },
  },
};

export const FLOWS = [
  { from: 'orchestrator', to: 'planner', label: 'Task Brief', type: 'primary' },
  { from: 'orchestrator', to: 'researcher', label: 'Query', type: 'primary' },
  { from: 'orchestrator', to: 'executor', label: 'Action Spec', type: 'primary' },
  { from: 'planner', to: 'orchestrator', label: 'Execution Plan', type: 'return' },
  { from: 'researcher', to: 'orchestrator', label: 'Research Data', type: 'return' },
  { from: 'executor', to: 'critic', label: 'Draft Output', type: 'primary' },
  { from: 'critic', to: 'refiner', label: 'Feedback (REFINE)', type: 'feedback' },
  { from: 'critic', to: 'orchestrator', label: 'PASS ✓', type: 'return' },
  { from: 'refiner', to: 'critic', label: 'Refined Output', type: 'loop' },
  { from: 'executor', to: 'error_handler', label: 'Error Report', type: 'error' },
  { from: 'error_handler', to: 'orchestrator', label: 'Recovery Plan', type: 'error' },
  { from: 'orchestrator', to: 'memory', label: 'Store Context', type: 'memory' },
  { from: 'memory', to: 'orchestrator', label: 'Recall Context', type: 'memory' },
  { from: 'memory', to: 'planner', label: 'Historical Plans', type: 'memory' },
  { from: 'memory', to: 'researcher', label: 'Cached Data', type: 'memory' },
];

export const PIPELINE_STEPS = [
  {
    step: 1,
    agent: 'orchestrator',
    action: 'Receive & Decompose Task',
    detail: 'Parse user input → extract intent, constraints, domain → build subtask queue',
    status: 'active',
  },
  {
    step: 2,
    agent: 'planner',
    action: 'Strategic Planning',
    detail: 'Build dependency DAG → estimate resources → assign agent types to subtasks',
    status: 'pending',
  },
  {
    step: 3,
    agent: 'researcher',
    action: 'Parallel Research',
    detail: 'Query KB + external APIs → rank sources → return summaries with confidence',
    status: 'pending',
  },
  {
    step: 4,
    agent: 'executor',
    action: 'Execute Actions',
    detail: 'Run tools, generate code, call APIs → produce artifacts with execution logs',
    status: 'pending',
  },
  {
    step: 5,
    agent: 'critic',
    action: 'Quality Evaluation',
    detail: 'Score output 0-100 → PASS / REFINE / REJECT based on rubric',
    status: 'pending',
  },
  {
    step: 6,
    agent: 'refiner',
    action: 'Iterative Refinement',
    detail: 'Apply targeted fixes from Critic feedback → re-evaluate (max 5 iterations)',
    status: 'pending',
  },
  {
    step: 7,
    agent: 'orchestrator',
    action: 'Aggregate & Respond',
    detail: 'Merge verified outputs → format final response → store to Memory',
    status: 'pending',
  },
];

export const ERROR_STRATEGIES = [
  { type: 'Transient Failure', strategy: 'Exponential Backoff Retry', icon: '🔄', color: '#f59e0b' },
  { type: 'Logic Error', strategy: 'Re-route to Alternate Agent', icon: '↪️', color: '#6366f1' },
  { type: 'Timeout', strategy: 'Partial Result + Continuation Token', icon: '⏱️', color: '#ec4899' },
  { type: 'Resource Exhaustion', strategy: 'Queue Deferral + Load Balancer', icon: '📦', color: '#10b981' },
  { type: 'Hallucination Detected', strategy: 'Force Researcher Verification', icon: '🚨', color: '#ef4444' },
  { type: 'Max Iterations Exceeded', strategy: 'Graceful Degradation + Human Escalation', icon: '⛔', color: '#64748b' },
];

export const SCALABILITY_FEATURES = [
  {
    title: 'Horizontal Agent Scaling',
    description: 'Each agent type runs as a stateless microservice. Kubernetes auto-scales pods based on queue depth.',
    icon: '📈',
  },
  {
    title: 'Message Queue Decoupling',
    description: 'Agents communicate via async message queues (Redis Streams / Kafka). No direct coupling.',
    icon: '📨',
  },
  {
    title: 'Agent Pool Registry',
    description: 'Dynamic registry tracks available agents, capabilities, and current load for smart routing.',
    icon: '🗂️',
  },
  {
    title: 'Circuit Breaker Pattern',
    description: 'Automatic circuit breaking prevents cascading failures across the agent network.',
    icon: '⚡',
  },
  {
    title: 'Distributed Memory',
    description: 'Vector DB (Pinecone/Weaviate) sharded across regions. Consistent reads via quorum.',
    icon: '🌐',
  },
  {
    title: 'Observability Stack',
    description: 'Every agent emits structured traces (OpenTelemetry). Dashboards in Grafana + Jaeger.',
    icon: '📊',
  },
];
